### ISSUE TITLE
Failed at the @ start script 'node build/dev-runner.js'.

### ISSUE THREAD

**Issue by nylira** [bradstewart/electron-boilerplate-vue#20]
I'm trying to get this boilerplate to run for the first time. I pull the repo, cd into it, and then `npm install`. It's erroring at `npm start`. My system node is at `6.1.0` if it matters.

```
**Error opening app***
The app provided is not a valid Electron app, please read the docs on how to write one:
https://github.com/atom/electron/tree/v0.37.2/docs

Error: Cannot find module '/Users/pz/Projects/electron-boilerplate-vue/dist'
```

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/6.1.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.9.0
3 info using node@v6.1.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @~prestart: @
6 silly lifecycle @~prestart: no script for prestart, continuing
7 info lifecycle @~start: @
8 verbose lifecycle @~start: unsafe-perm in lifecycle true
9 verbose lifecycle @~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/pz/Projects/electron-boilerplate-vue/node_modules/.bin:/usr/local/Cellar/node/6.1.0/bin:/Users/pz/.cabal/bin:/Users/pz/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/pz/.cabal/bin:/Users/pz/anaconda3/bin:/Users/pz/annex/go/bin:/Users/pz/annex/go/bin
10 verbose lifecycle @~start: CWD: /Users/pz/Projects/electron-boilerplate-vue
11 silly lifecycle @~start: Args: [ '-c', 'node build/dev-runner.js' ]
12 silly lifecycle @~start: Returned: code: 1  signal: null
13 info lifecycle @~start: Failed to exec start script
14 verbose stack Error: @ start: `node build/dev-runner.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid @
16 verbose cwd /Users/pz/Projects/electron-boilerplate-vue
17 error Darwin 15.4.0
18 error argv "/usr/local/Cellar/node/6.1.0/bin/node" "/usr/local/bin/npm" "start"
19 error node v6.1.0
20 error npm  v3.9.0
21 error code ELIFECYCLE
22 error @ start: `node build/dev-runner.js`
22 error Exit status 1
23 error Failed at the @ start script 'node build/dev-runner.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the  package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node build/dev-runner.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by nylira** [comment]
Ah, this is duplicate of #18. Closing.
