### ISSUE TITLE
Unmet peer dependency electron-prebuilt

### ISSUE THREAD

**Issue by rdpascua** [bradstewart/electron-boilerplate-vue#30]
Fresh installation gives me this error.

UNMET PEER DEPENDENCY electron-prebuilt@>=0.35.0

``` bash
npm ERR! Linux 3.19.0-59-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.4.1
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@1.1.0 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-prebuilt@1.1.0 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

```

UPDATE:

``` bash
             return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                             ^

            Error: ENOENT: no such file or directory, open '/storage/projects/foo/node_modules/electron-prebuilt/path.txt'
                at Error (native)
                at Object.fs.openSync (fs.js:634:18)
                at Object.fs.readFileSync (fs.js:502:33)
                at Object.<anonymous> (/storage/projects/foo/node_modules/electron-prebuilt/index.js:4:42)
                at Module._compile (module.js:541:32)
                at Object.Module._extensions..js (module.js:550:10)
                at Module.load (module.js:458:32)
                at tryModuleLoad (module.js:417:12)
                at Function.Module._load (module.js:409:3)
                at Module.require (module.js:468:17)

```

**Comment by rdpascua** [comment]
In attempt to resolve the issue, I removed the electron cache folder

```
rm -rf ~/.electron
npm install electron-prebuilt --save-dev
```

**Comment by davidmoshal** [comment]
Didn't work for me, though I got a different error after trying your suggestions:

```
 npm i

> nslog@3.0.0 install /Users/clive/Documents/vue/my-project/node_modules/nslog
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR


Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.



gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR


Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.


gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 69
gyp ERR! stack     at ChildProcess.onExit (/Users/clive/.nvm/versions/node/v6.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/Users/clive/.nvm/versions/node/v6.6.0/bin/node" "/Users/clive/.nvm/versions/node/v6.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/clive/Documents/vue/my-project/node_modules/nslog
gyp ERR! node -v v6.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
my-project@0.0.0 /Users/clive/Documents/vue/my-project
└── (empty)

npm WARN my-project@0.0.0 No repository field.
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/clive/.nvm/versions/node/v6.6.0/bin/node" "/Users/clive/.nvm/versions/node/v6.6.0/bin/npm" "i"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! nslog@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nslog
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/clive/Documents/vue/my-project/npm-debug.log
npm ERR! code 1
```

**Comment by davidmoshal** [comment]
Then I typed this (on OSX): 
`sudo xcodebuild -license` 
and tried again - success !
